#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# git plugins
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/runcoms/git-plugin" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/runcoms/git-plugin"
fi

export EDITOR=/usr/local/bin/vim
export VISUAL=/usr/local/bin/vim
